In [4]:
import pandas as pd

leads_data = []
print("Lead Qualification System Initialized!")

Lead Qualification System Initialized!

In [5]:
def calculate_budget_score(budget):
    # Budget above 3000: 30 points, 1000-3000: 20 points, below 1000: 10 points
    if budget > 3000:
        return 30
    elif 1000 <= budget <= 3000:
        return 20
    else:
        return 10

def calculate_urgency_score(urgency):
    # Immediate: 30, This month: 20, Later: 10
    urg_lower = urgency.lower().strip()
    if urg_lower == "immediate":
        return 30
    elif urg_lower == "this month":
        return 20
    else:
        return 10

def calculate_decision_maker_score(is_decision_maker):
    # Yes: 30 points, No: 10 points
    dm_lower = is_decision_maker.lower().strip()
    if dm_lower == "yes":
        return 30
    else:
        return 10

def classify_lead(total_score):
    # 70 and above: Hot, 40 to 69: Warm, Below 40: Cold
    if total_score >= 70:
        return "Hot Lead"
    elif 40 <= total_score <= 69:
        return "Warm Lead"
    else:
        return "Cold Lead"

def add_lead(name, company, budget, urgency, service, decision_maker):
    b_score = calculate_budget_score(budget)
    u_score = calculate_urgency_score(urgency)
    dm_score = calculate_decision_maker_score(decision_maker)
    
    total_score = b_score + u_score + dm_score
    classification = classify_lead(total_score)
    
    lead = {
        "Name": name,
        "Company": company,
        "Budget": budget,
        "Urgency": urgency,
        "Service Needed": service,
        "Decision Maker": decision_maker,
        "Total Score": total_score,
        "Classification": classification
    }
    leads_data.append(lead)
    print(f"\n[System]: Lead for '{name}' from '{company}' has been recorded successfully. Status: {classification}")

def display_leads():
    if not leads_data:
        print("\n[Error]: No leads recorded in the system yet.")
        return None
    return pd.DataFrame(leads_data)

def filter_hot_leads():
    if not leads_data:
        print("\n[Error]: No leads recorded in the system yet.")
        return None
    df = pd.DataFrame(leads_data)
    hot_leads_df = df[df["Classification"] == "Hot Lead"]
    if hot_leads_df.empty:
        print("\n[Info]: No Hot Leads found matching the criteria.")
        return None
    return hot_leads_df

def generate_report():
    if not leads_data:
        print("\n[Error]: No data available to generate the final report.")
        return
    
    df = pd.DataFrame(leads_data)
    total_leads = len(df)
    hot_count = len(df[df["Classification"] == "Hot Lead"])
    warm_count = len(df[df["Classification"] == "Warm Lead"])
    cold_count = len(df[df["Classification"] == "Cold Lead"])
    avg_score = df["Total Score"].mean()
    
    best_lead = df.loc[df["Total Score"].idxmax()]["Name"]
    best_company = df.loc[df["Total Score"].idxmax()]["Company"]
    
    print("\n================ 📊 SYSTEM EXECUTIVE REPORT ================")
    print(f"1. Total Processed Leads      : {total_leads}")
    print(f"2. Total Hot Leads Classified : {hot_count}")
    print(f"3. Total Warm Leads Classified: {warm_count}")
    print(f"4. Total Cold Leads Classified: {cold_count}")
    print(f"5. Average Lead Quality Score : {avg_score:.2f}")
    print(f"6. Primary Priority Contact   : {best_lead} (Company: {best_company})")
    print("============================================================")

In [6]:
while True:
    print("\n--- 🎯 LEAD QUALIFICATION & SCORING SYSTEM ---")
    print("1. Add New Lead")
    print("2. View All Leads")
    print("3. View Hot Leads Only")
    print("4. Generate Executive Report")
    print("5. Exit System")
    
    choice = input("\nEnter your choice (1-5): ")
    
    if choice == '1':
        print("\n[Input]: Please enter the following lead details:")
        name = input("Enter contact name: ")
        company = input("Enter company name: ")
        budget = float(input("Enter budget (in $): "))
        urgency = input("Enter urgency (Immediate / This month / Later): ")
        service = input("Enter service needed: ")
        decision_maker = input("Is the contact a decision maker? (Yes / No): ")
        
        add_lead(name, company, budget, urgency, service, decision_maker)
        
    elif choice == '2':
        df_all = display_leads()
        if df_all is not None:
            print("\n================ 📋 ALL REGISTERED LEADS ================")
            display(df_all)
            print("=========================================================")
            
    elif choice == '3':
        print("\n[System]: Fetching prioritized Hot Leads (Score >= 70)...")
        df_hot = filter_hot_leads()
        if df_hot is not None:
            print("\n================ 🔥 ACTIVE HOT LEADS ====================")
            display(df_hot)
            print("=========================================================")
            
    elif choice == '4':
        generate_report()
        
    elif choice == '5':
        print("\n[System]: Shutting down the system. Session ended successfully. Goodbye!")
        break
        
    else:
        print("\n[Error]: Invalid selection! Please enter a valid choice between 1 and 5.")

--- 🎯 LEAD QUALIFICATION & SCORING SYSTEM ---
1. Add New Lead
2. View All Leads
3. View Hot Leads Only
4. Generate Executive Report
5. Exit System

Enter your choice (1-5):  1

[Input]: Please enter the following lead details:

Enter contact name:  muzz
Enter company name:  muzzAI
Enter budget (in $):  100
Enter urgency (Immediate / This month / Later):  immediate
Enter service needed:  Automation
Is the contact a decision maker? (Yes / No):  yes

[System]: Lead for 'muzz' from 'muzzAI' has been recorded successfully. Status: Hot Lead

--- 🎯 LEAD QUALIFICATION & SCORING SYSTEM ---
1. Add New Lead
2. View All Leads
3. View Hot Leads Only
4. Generate Executive Report
5. Exit System

Enter your choice (1-5):  1

[Input]: Please enter the following lead details:

Enter contact name:  ali
Enter company name:  ALIui
Enter budget (in $):  200
Enter urgency (Immediate / This month / Later):  later
Enter service needed:  plumbering
Is the contact a decision maker? (Yes / No):  no

[System]: Lead for 'ali' from 'ALIui' has been recorded successfully. Status: Cold Lead

--- 🎯 LEAD QUALIFICATION & SCORING SYSTEM ---
1. Add New Lead
2. View All Leads
3. View Hot Leads Only
4. Generate Executive Report
5. Exit System

Enter your choice (1-5):  2

================ 📋 ALL REGISTERED LEADS ================

,Name,Company,Budget,Urgency,Service Needed,Decision Maker,Total Score,Classification
0,muzz,muzzAI,100.0,immediate,Automation,yes,70,Hot Lead
1,ali,ALIui,200.0,later,plumbering,no,30,Cold Lead

=========================================================

--- 🎯 LEAD QUALIFICATION & SCORING SYSTEM ---
1. Add New Lead
2. View All Leads
3. View Hot Leads Only
4. Generate Executive Report
5. Exit System

Enter your choice (1-5):  3

[System]: Fetching prioritized Hot Leads (Score >= 70)...

================ 🔥 ACTIVE HOT LEADS ====================

,Name,Company,Budget,Urgency,Service Needed,Decision Maker,Total Score,Classification
0,muzz,muzzAI,100.0,immediate,Automation,yes,70,Hot Lead

=========================================================

--- 🎯 LEAD QUALIFICATION & SCORING SYSTEM ---
1. Add New Lead
2. View All Leads
3. View Hot Leads Only
4. Generate Executive Report
5. Exit System

Enter your choice (1-5):  4

================ 📊 SYSTEM EXECUTIVE REPORT ================
1. Total Processed Leads      : 2
2. Total Hot Leads Classified : 1
3. Total Warm Leads Classified: 0
4. Total Cold Leads Classified: 1
5. Average Lead Quality Score : 50.00
6. Primary Priority Contact   : muzz (Company: muzzAI)
============================================================

--- 🎯 LEAD QUALIFICATION & SCORING SYSTEM ---
1. Add New Lead
2. View All Leads
3. View Hot Leads Only
4. Generate Executive Report
5. Exit System

Enter your choice (1-5):  5

[System]: Shutting down the system. Session ended successfully. Goodbye!